// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: proto/master.proto

package distributed_grep

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Il messaggio di richiesta client-master
type GrepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Regex    string `protobuf:"bytes,2,opt,name=regex,proto3" json:"regex,omitempty"`
}

func (x *GrepRequest) Reset() {
	*x = GrepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepRequest) ProtoMessage() {}

func (x *GrepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepRequest.ProtoReflect.Descriptor instead.
func (*GrepRequest) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{0}
}

func (x *GrepRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GrepRequest) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

// il messaggio di risposta master-client
type GrepResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows  string `protobuf:"bytes,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GrepResult) Reset() {
	*x = GrepResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepResult) ProtoMessage() {}

func (x *GrepResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepResult.ProtoReflect.Descriptor instead.
func (*GrepResult) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{1}
}

func (x *GrepResult) GetRows() string {
	if x != nil {
		return x.Rows
	}
	return ""
}

func (x *GrepResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_master_proto protoreflect.FileDescriptor

var file_proto_master_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0b, 0x47,
	0x72, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x67, 0x65, 0x78, 0x22, 0x36, 0x0a,
	0x0a, 0x47, 0x72, 0x65, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x77, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x42, 0x0a, 0x06, 0x47, 0x6f, 0x47, 0x72, 0x65, 0x70, 0x12,
	0x38, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x47, 0x72,
	0x65, 0x70, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x65, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x72, 0x65, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x64, 0x6a, 0x61, 0x63, 0x6b, 0x3b,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x72, 0x65, 0x70,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_master_proto_rawDescOnce sync.Once
	file_proto_master_proto_rawDescData = file_proto_master_proto_rawDesc
)

func file_proto_master_proto_rawDescGZIP() []byte {
	file_proto_master_proto_rawDescOnce.Do(func() {
		file_proto_master_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_master_proto_rawDescData)
	})
	return file_proto_master_proto_rawDescData
}

var file_proto_master_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_master_proto_goTypes = []interface{}{
	(*GrepRequest)(nil), // 0: proto.GrepRequest
	(*GrepResult)(nil),  // 1: proto.GrepResult
}
var file_proto_master_proto_depIdxs = []int32{
	0, // 0: proto.GoGrep.DistributedGrep:input_type -> proto.GrepRequest
	1, // 1: proto.GoGrep.DistributedGrep:output_type -> proto.GrepResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_master_proto_init() }
func file_proto_master_proto_init() {
	if File_proto_master_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_master_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_master_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrepResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_master_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_master_proto_goTypes,
		DependencyIndexes: file_proto_master_proto_depIdxs,
		MessageInfos:      file_proto_master_proto_msgTypes,
	}.Build()
	File_proto_master_proto = out.File
	file_proto_master_proto_rawDesc = nil
	file_proto_master_proto_goTypes = nil
	file_proto_master_proto_depIdxs = nil
}
